name: Kitsune
version: '${version}'
main: dev.jlo.kitsune.spigot.SpigotPlugin
api-version: '1.21.4'
description: Semantic nearby storage search
softdepend: [LWC]
commands:
  kitsune:
    description: Search nearby storage
    usage: /kitsune [--verbose] <query>
    permission: kitsune.search
permissions:
  kitsune.search:
    description: Search nearby accessible storage
    default: true
