name: ChestFind
version: 1.0-SNAPSHOT
main: org.aincraft.chestfind.ChestFindPlugin
api-version: 1.21
author: YourName
description: "Find chests using semantic search commands"
website: "https://github.com/yourusername/chestfind"

commands:
  find:
    description: "Find items in chests using semantic search"
    usage: "/find <query>"
    permission: chestfind.use
    permission-message: "You don't have permission to use the find command"

permissions:
  chestfind.use:
    description: "Allows user to search for items in chests"
    default: true
  chestfind.admin:
    description: "Allows user to use admin commands"
    default: op