name: Kitsune
version: 1.0-SNAPSHOT
main: org.aincraft.kitsune.KitsunePlugin
bootstrapper: org.aincraft.kitsune.KitsuneBootstrap
api-version: "1.21"
description: "Find chests using semantic search with vector embeddings"
author: YourName
website: "https://github.com/yourusername/kitsune"

permissions:
  kitsune.use:
    description: "Allows user to search for items in chests"
    default: true
  kitsune.admin:
    description: "Allows user to use admin commands (reload, stats, reindex)"
    default: op
