[versions]
junit = "5.14.4"
sqlite = "3.53.2.1"
paper-api = "1.21.4-R0.1-SNAPSHOT"
spigot-api = "1.21.4-R0.1-SNAPSHOT"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
